### ISSUE TITLE
Purchasing Module

### ISSUE THREAD

**Issue by rosoarv** [dev-tea-party/dev-access#54]
- [x] Generate CRUD Operations for Purchase Orders - https://github.com/dev-tea-party/dev-access/issues/48
- [x] Suppliers
- Use dropdown instead of form input in Suppliers field
- Use suppliers as options for dropdown
- Display supplier name instead of Supplier ID
- [x] Prepared By and Approved By
- Display Name of User in show view
- Save current logged_in user_id during submission
- Remove Prepared By and Approved By fields
- Add Status (Pending, Approved, Denied) column in Purchase Order list
- [ ] Modify Form interface. Refer to Purchasing Module wireframe
- [ ] Add List of Items to be Purchased
- [ ] Add Validation

**Note: Create new issues per checkbox. Reference new issue link in this issue beside checkbox title**

**Comment by litocabornay** [comment]
will start working this module today.
